---
title       : Shiny Lightning Talk
subtitle    : 
author      : Christina Brady
job         : Data Scientist, World Bank
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---&vcenter
## What is Shiny?

### Shiny is an R package that allows you to create web apps from R.

--- &vcenter
## So?

### You can create [sign up forms] (http://52.42.38.111:3838/challenger_signups/)
### You can [organize your recipes] (http://52.42.38.111:3838/recipe_app/)
### You can [automate annoyings tasks] (http://52.42.38.111:3838/un_code_search/)
### You can predict if you will survive your visit to the [known world] (http://52.42.38.111:3838/GoT_survival/)
### Many other [things] (http://www.showmeshiny.com/)

--- &vcenter
## Do I need a web server?

### There are several ways to run a Shiny App:
### * From within R (opens in a browser)
### * In Rstudio (opens in Rstudio viewer)
### * Shiny Server on a server

--- &vcenter
## What else can I do with Shiny?

### Connect to databases to store data
### Connect to Google Docs to store data
### Import and export files
### Include HTML files
### Inclue maps (leaflet, GoogleVis, rMaps)
### Include interactive visualizations (ggvis)

--- &vcenter
## How do I get started?

### Rstudio [tutorial] (http://shiny.rstudio.com/tutorial/)
### Stackoverflow

--- &vcenter
## Thank you

## Christina Brady
# email: christina.brady@gmail.com
# github: www.github.com/christinabrady

